### ISSUE TITLE
Passing options to app.io()

### ISSUE THREAD

**Issue by jameswyse** [techpines/express.io#1]
Would it be possible to pass options to socket.io before starting the server? Basically my problem is that I use a custom logger and I still get "info  - socket.io started" in my console, so I'd like to pass it before the listen event.

Normally it'd be something like this:

``` javascript
io.listen(app, { log: false });
```

I'm afraid I don't speak coffee-script too well, but I noticed that `express.application.io` accepts `options` and doesn't appear to use it, so changing the first line to:

``` coffee-script
@io = io.listen @server, options
```

Should do what I'm after? Let me know what you think.

**Comment by techpines** [comment]
Yes, you're right.

Do you want to do a pull request, so you can get credit for the fix?

Otherwise, I'll just make the change some time tomorrow.

**Comment by jameswyse** [comment]
Great project by the way - I was lucky to stumble upon it before I started writing the same thing! Cheers!
