### ISSUE TITLE
Endless connections with browserified socket io client

### ISSUE THREAD

**Issue by werty1st** [techpines/express.io#129]
Hi,

i try to use express.io with a browserified socket io client.

Server:

``` javascript
var express  = require('express.io');
var app      = express().http().io();
app.io.route('already', function(req) {
    console.log("app io ready");
});
```

Client:
(browserify js_src/client.js -o public/bundle.js)

``` javascript
var io = require('socket.io-client');
io.connect();
socket.emit('already');
```

The result are endless request like:
- http://localhost:8881/socket.io/?EIO=3&transport=polling&t=1448304185035-1
- http://localhost:8881/socket.io/?EIO=3&transport=polling&t=1448304185074-2
  ![Console](http://s17.postimg.org/miy4wwszz/Bildschirmfoto_vom_2015_11_23_19_43_51.png)

If i embed the script like this its working, but not browserfied :(

``` html
<script src="/socket.io/socket.io.js"></script> 
<script type="text/javascript">
        socket = io.connect();
        socket.emit('already');
</script>
```

How can i resolve this?

**Comment by werty1st** [comment]
if one uses

``` javascript
var io = require("socket.io-browserify");
```

instead of

``` javascript
var io = require("socket.io-client");
```

it works.

but i can't explain why.

**Comment by charleston10** [comment]
Which file you upgraded? I've the same problem

**Comment by werty1st** [comment]
the base JS file which will be browserified.

# client.js

``` javascript
var io = require("socket.io-browserify");
var socket = io.connect();
socket.on("render", { target: "agent1" } ,function(data) {
  console.info("sessiondata event received. Check the console");
});
socket.emit('already');
```

# convert

``` bash
browserify browser/main.js | uglifyjs -mc > static/bundle.js
```

# index.html

``` html
<script src="/bundle.js" ></script>
```
