### ISSUE TITLE
Cannot find module...

### ISSUE THREAD

**Issue by muZk** [techpines/express.io#16]
Hey, just tried to install express.io and got an error

$ node server

module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/express/node_modules/connect'

**Comment by jameswyse** [comment]
That's due to this: https://github.com/techpines/express.io/blob/master/lib/index.coffee#L1

It's a weird way to require('connect') but it should work anyway, did you run `npm install` in your app's directory?

**Comment by techpines** [comment]
Basically, I was trying to make sure that I was getting the same version of connect that comes with express.  What platform are you on?

If this doesn't work for some reason, then I'll change it back.

**Comment by jameswyse** [comment]
It works fine for me :) That makes sense though but I guess you can't guarantee that the directory will be correct on every system. It would be handy if Express exposed connect for this common use case :/

I think you can also do something like: `require('express/node_modules/connect');` which should at least search for the base `node_modules` folder where express resides.

**Comment by techpines** [comment]
@jameswyse  That's awesome!

@muZk Alright, I made that change, try the latest version:

``` js
express.io@1.1.11
```

**Comment by muZk** [comment]
I was working on win7.

@techpines @jameswyse  it works fine now, thankz!
