### ISSUE TITLE
Using express.io with vhosts

### ISSUE THREAD

**Issue by cflynn07** [techpines/express.io#18]
I've been looking into express.io for a while and so far it's great. I'm about to try and divvy up some routes in my application on different subdomains, ('api.foo.com' && 'www.foo.com'), is there anything express.io specific that I should consider?

**Comment by techpines** [comment]
@cflynn07 I don't see any problem using virtual hosts with express.io. 

But if you run into any issues please let me know.

**Comment by techpines** [comment]
@cflynn07 Did you ever run into any trouble with this?

**Comment by cflynn07** [comment]
Hey @techpines, nope it worked perfectly. :+1: thanks!
