### ISSUE TITLE
Accessing the data store session from all the connections within a room?

### ISSUE THREAD

**Issue by ghost** [techpines/express.io#29]
Hello there,

Currently in order to get the list of clients within a room (apart from the Req.io) I am using the following code:

var roomContacts = globalVar.https.io.sockets.clients('1');

for(var index = 0; index < roomContacts.length; index++)
    if(roomContacts[index] != Request.socket)
        readyArray.push(roomContacts[index]); // Reference to the socket

However, I am required to index certain pieces of data (in this case the email user account associated with the connection). These pieces of data are stored in the Request.Session and I can't seem to find a proper way to retrieve such data from outside the current Request.

I have checked the documentation but I don;t think there is any interface that allows such functionality, any ideas or suggestions?

Regards,

Alex.

**Comment by techpines** [comment]
If I understand correctly, you want to get to the session data of another client connected by websockets?

If that data needs to be pertinent/accessible across you application, then I would consider maybe storing it somewhere else like a database.

To get to another clients session you would need that clients sessionId.  

One thing you could try would be to send a broadcast to all of the clients in that room, and then have them respond to you with their socketId or sessionId, although this is probably not the best solution.  

I'm not sure if socket.io provides an easy way to get everybody in a certain room.  Another idea might be to put everyone in a room for their email address.  That way you'd have a way to talk to anybody via there email if you knew that (basically a room with one client in it).

Best of luck!
