### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by jameswyse** [techpines/express.io#3]
Hello! I'm trying to set up an API which is available via both REST routes and socket.io.

I noticed in your 'advanced routing' example that you can specify routes like:

``` javascript
app.io.route('collection', {
    get: collectionGet,
    post: collectionPost
});
```

I can access this on the client side easily, however how do you access them for route forwarding?

I tried:

``` javascript
app.get('/collection/:resourceName', function(req, res) {
    req.io.route('collection:get');
});
```

which didn't work:
`TypeError: Object #<Object> has no method 'collection:get'`

**Comment by techpines** [comment]
@jameswyse It should work now.  Your syntax above is correct.  I bumped the npm version to 1.1.6.

I was also thinking about throwing in an extra set of middleware.

``` js
app.use('/api', express.io.routeForward(options))
```

With the idea being, that if you followed some simple convention with your io routes, then you could get a rest api for free by adding some middleware. 

I know backbone.js has a convention for CRUD/REST that looks like this:
- create → POST   /collection
- read → GET   /collection[/id]
- update → PUT   /collection/id
- delete → DELETE   /collection/id

so then you could do this in the io route, and have it automatically sync up without defining the express routes explicitly:

``` js
app.io.route('collection', {
    create: function(req) {

    },
    read: function(req) {

    },
    update: function(req) {

    },
    delete: function(req) {

    }
})
```

**Comment by jameswyse** [comment]
Great, thanks!

That sounds like a good idea to me, it's basically what I'm doing currently. AngularJS has a similar convention, defining CRUD/REST routes allows you to access the entire thing with just one line:

`var UsersDB = $resource('/api/resources/users/:id', { id: '@_id' });`

from routes like:
-  list → GET /api/resources/:resourceName
-  create → POST /api/resources/
-  read → GET /api/resources/:resourceName/:id
-  update → PUT /api/resources/:resourceName/:id
-  delete → DELETE /api/resources/:resourceName/:id
