### ISSUE TITLE
Unable to upload files?

### ISSUE THREAD

**Issue by DevDavido** [techpines/express.io#30]
HTML:

``` html
<form method="post" enctype="multipart/form-data" action="/upload">
    <input type="file" name="test" />
    <input type="submit" value="Upload" />
</form>
```

App:

``` js
app.io.configure(function() {
    app.use(express.bodyParser({ uploadDir: __dirname + '/uploads', limit: 5 * 1000000, keepExtensions: true, defer: true }));
});


app.post('/upload', function(req, res) {
    console.log(req.files);
});
```

And `req.files` is always an empty `{}`.
Am I doing something wrong or is there a bug in express.io?
If the mistake is on my side: Please add an example for file uploads.

Update:
The files getting uploaded, but as I mentioned I don't have any information about them via express(.io).

**Comment by techpines** [comment]
Maybe try moving your `app.use` directive outside of `app.io.configure`.

I've used file uploads before, and there shouldn't be any difference between how express and express.io handles them.

Best!

**Comment by DevDavido** [comment]
Thanks for the fast reply :+1: !
It didn't change anything what I get for `req.files` if I move my configuration outside of `app.io.configure`:

``` js
app.io.set('log level', 2);
app.io.set('transports', 'websocket');
app.io.set('views', __dirname + '/views/')

app.use(express.compress());
app.use(express.cookieParser('secret'));
app.use(express.bodyParser({ uploadDir: __dirname + '/uploads', limit: 1 * 1000 * 1000, keepExtensions: true, defer: true }));
app.use(express.session({
    signed: true,
    secret: 'secret',
    store: new MongoStore({
        db: db
    }),
    cookie: {
        maxAge: 30 * 24 * 60 * 60 * 1000,
        httpOnly: true
    }
}));
```

Could you test/try it?

**Comment by DevDavido** [comment]
I simplified it for copy&paste testing:

``` js
var fs = require('fs');
var express = require('express.io');

var app = express().http().io();
app.use(express.bodyParser({
    uploadDir: __dirname + '/uploads',
    limit: 1000000,
    keepExtensions: true,
    defer: true
}));

// Route requests
app.get('/', function(req, res) {
    fs.readFile('form.html', function(err, page) {
        res.writeHead(200, {'Content-Type': 'text/html'});
        res.write(page);
        res.end();
    });
});

app.post('/upload', function(req, res) {
    console.log(req.files);
    console.log(req);
});

app.listen(80);
console.log('Server is running...');
```

form.html

``` html
<form method="post" enctype="multipart/form-data" action="/upload" >
    <input type="file" name="image" />
    <input type="submit" value="Upload" />
</form>
```

It would be great to make it work, because I'm struggling already for 2 days on this problem and there is no module or even no code which works.

**Comment by jameswyse** [comment]
Remove `defer: true` from the bodyParser options, I'm not sure what that is meant to do but for some reason it prevents req.files being populated!

edit: Ah, when you have `defer: true` it exposes the raw formidable form object to express as `req.form`. I guess it's for more advanced operations :)

**Comment by DevDavido** [comment]
Awesome @jameswyse :+1: !
Finally it works as it should, thank you very much.

**Comment by rohit8** [comment]
Unfortunately, I am facing the same issue with this method even if the 'defer: true' parameter is removed in express.bodyParser(). @DevDavido / @jameswyse, is there anything else that you did in order to have access to req.files? It is still undefined for me. I appreciate your help in advance.

Thanks,
Rohit
