### ISSUE TITLE
Emit with app.io

### ISSUE THREAD

**Issue by hydrotik** [techpines/express.io#33]
app.io.emit('growl', 'Your project has been created');

Doesn't seem to be working. I know that req.io.emit('event', {this: 'is sent as an event to the client'}) only sends to the client, but is there a way to do this outside of an io.route callback? 

Thanks!

**Comment by hydrotik** [comment]
I'm also trying to do this with route forwarding and that isn't working either. I noticed that console.log(req.io.emit); is undefined in both the normal express route as well as the io route. Im guessing the relationship between the client and the server isn't established in the way I'm trying to make this happen? I'm using normal express routing for my site and figured I'd use express.io for notifications, but wondering if this isn't the path to take.

**Comment by hydrotik** [comment]
So I decided to go with connect flash for the obvious reasons. Plenty of practical use cases to use express.io, direct client alerts is totally overkill:) But I can see a case where using rooms to limit alerts to users in a specific sandbox would be fun. Cheers.

**Comment by techpines** [comment]
https://github.com/techpines/express.io/tree/master/lib#appio

Should be:

``` js
app.io.broadcast
```

Also, you might check out http://bone.io, which is another realtime library that I wrote, cheers!

**Comment by hydrotik** [comment]
Doesn't that go to all clients except yourself? I need to send just to the client. Seems like a req or a response is the only way to do it. I'll check out bone.io. Look interesting. Cheers.

**Comment by techpines** [comment]
@hydrotik Yes, you're right, but in this case you're broadcasting for the entire app not from an individual socket.
