### ISSUE TITLE
Emit to a particular user

### ISSUE THREAD

**Issue by american423** [techpines/express.io#5]
I want to "emit" a message to a particular client. 

Now I am doing like this 
app.io.sockets.sockets[socket.id].emit('news',{msg:"something"});

Is this correct way?

Thank you

**Comment by techpines** [comment]
I would use rooms.

I think the way that you're currently doing it might work for now, but it probably won't work when you have more than one node process.

With rooms you would have each client join a room initially:

``` js
app.io.route('ready', function(req) {
    var userId = 'abc123' // genreate some kind of unique id for the user
    req.io.join(userId) // now join a room based on the userId
})
```

Now everyone one else can reach this person by broadcasting to his room:

``` js
req.io.room('abc123').broadcast('hello') 
```

**Comment by american423** [comment]
This is great idea! Thank you for your comment.

I will use "join" and "room" !
