### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by pharcosyle** [techpines/express.io#53]
Hey, looks like the dependencies are getting a bit behind (namely express and socket.io). Since these are basically the backbone of my entire application I'd feel better seeing these updated. I submit a pull request if need be.

**Comment by Thomasdezeeuw** [comment]
I agree. They're shouldn't be any changes to the api, so I don't see a reason it is taking this long...

**Comment by techpines** [comment]
Will update soon.

**Comment by techpines** [comment]
Dun.

```
express.io@1.13
```

**Comment by Thomasdezeeuw** [comment]
Great to hear that :)
