### ISSUE TITLE
[question] session expires

### ISSUE THREAD

**Issue by pharcosyle** [techpines/express.io#7]
Will express.io ensure that sessions don't expire an app is being used?

A session won't expire while http requests are being issued but if the app uses only socketio after the initial pageload it seems like this could happen.

This possible problem with express/socketio session sharing is brought up in this thread, if I'm not explaining it well enough: http://www.danielbaulig.de/socket-ioexpress/

**Comment by techpines** [comment]
@pharcosyle I believe you are correct.  Express.io is not automatically saving session state on each socket.io request.  

You can manage this from your routes by using the touch method (which updates `maxAge` for the session):

``` js
app.io.route('some-route', function(req) {
    req.session.touch();
    // repond to this request
});
```

I believe this means that if you had only io requests coming in, then yes your session could expire if you did not update it manually with `session#touch` or `session#save`.

Is this a big issue for you?  I am thinking about a few different concepts for middleware, and I would be more than happy to hear about your use case and how different middleware solutions might help.

Cheers!

**Comment by pharcosyle** [comment]
It's not an issue for me at all, at least not yet, just something I had identified as a probable future need in my own implementation of all this stuff (before I discovered express.io)

**Comment by techpines** [comment]
Closing for now.
