### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by DanieleSalatti** [techpines/express.io#78]
Hi

Is this still maintained?

**Comment by nullivex** [comment]
Not sure, I havent seen much activity out of the original author. Lots of people seem interested though.

**Comment by techpines** [comment]
Yes, it's sill maintained.

What issues do you think need to be resolved.

**Comment by wallynm** [comment]
I have used the original socket.io and got many problems using session, which made me switch to express.io that was really simple to implement and use, he also has all the features from socket.io...

**Comment by DanieleSalatti** [comment]
@techpines: we are going to use it for a new piece of software, just wanted to be sure it is still alive... :)
