### ISSUE TITLE
express 4.x support

### ISSUE THREAD

**Issue by tdzienniak** [techpines/express.io#80]
Is adding express 4.x support or simply migrating to it planned for near future? That will be cool.

**Comment by techpines** [comment]
Yes, we will be migrating soon.

**Comment by tdzienniak** [comment]
Good to hear, thanks!

**Comment by geoah** [comment]
Is there an eta on a alpha/beta version of this or should we start hacking up something for exp4 until it is released?! ^_^
Want to play around with something that express.io would be perfect for and have some spare time atm! :P -- don't mean to be rude or anything! ^_^

**Comment by veyDer** [comment]
I'm interested in using express.io in express 4.x too. So far I can't get sessions to work.

**Comment by hnrch02** [comment]
@techpines Any news on support for express 4? So far everything seems to work fine except for sessions, as @veyDer has mentioned.

**Comment by techpines** [comment]
Probably, in the next few weeks, unless I get a PR before then.

**Comment by hnrch02** [comment]
I'd send one, but I wouldn't know how to implement it from the now separate module.
