### ISSUE TITLE
Syntax to retrieve clients inside a specific room?

### ISSUE THREAD

**Issue by ghost** [techpines/express.io#9]
Greetings,
I have been converting some of my code base from standard express and socket.io to express.io and i cannot get my hand around how to retrieve the socket list without parsing specific attributes of either the app.io.room or req.io.room
Is there any specific syntax that will allow me to retrieve all the sockets in an array format like the standard io.sockets.clients(RoomID);?

Best Regards.

**Comment by techpines** [comment]
I believe you should be able to do this:

``` js
app.io.sockets.clients(RoomID)
```

In general, the `app.io` object should behave mostly like the the standard `io` object from socket.io.

**Comment by techpines** [comment]
You would route it like any other event:

``` js
app.io.route('disconnect', function (req) {
    console.log('Disconnected!!!');
});
```

I think the only event you can catch for every socket with socket.io is 'connection'.  Everything else has to be bound to the individual socket, which express.io does through the route function.

Check out their wiki docs here:

https://github.com/LearnBoost/socket.io/wiki/Exposed-events
