### ISSUE TITLE
Token authentication with socketio-jwt

### ISSUE THREAD

**Issue by zacharynevin** [techpines/express.io#92]
What would be the best way to implement token authentication in express.io? The reason I am asking this question here is because I only really seem to have a problem with the [socketio-jwt](https://github.com/auth0/socketio-jwt) library when used with express.io, so I'm really wondering if there is anything special I need to do

Currently I am trying to use the [socketio-jwt](https://github.com/auth0/socketio-jwt) library, but I am having problems integrating it, as described below.

**Description of socketio-jwt integration**
I really just followed the tutorial on the socketio-jwt GitHub page for this. My problem is that I can connect, but I can't do any authentication:

In my `app.js`, I have the following:

```
// extra stuff above 

app.io.sockets.on('connect', socketioJwt.authorize({
    secret: app.get('tokenSecret'),
    timeout: 15000 // 15 seconds
})).on('authenticated', function(req) {
    console.log('authenticated!');

    var user_id = req.decoded_token.user_id
    console.log(user_id)
    app.io.set('user_id', user_id);
    req.socket.join('notifications.' + user_id);    
})
```

On the client-side, I have the following:

```
<script src="/socket.io/socket.io.js"></script>
<script>
  var socket = io.connect('http://localhost');
  socket.on('connect', function() {
    console.log('connected!');
    socket.on('authenticated', function() {
        console.log('you are authenticated!')
    }).emit('authenticate', { token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJkYXRlT2ZJc3N1ZSI6MTQwMzE0OTY1Njc0OX0.VRsGFfWAd6l2cXZDlhZ7Px6v5ekA_MgfVBk9wn2mzuw' });
  });
</script>
```

I can connect just fine, it seems, as indicated by the `connected!` in the browser console. The problem is that the `socket.emit('authenticate', { token: data })` line does nothing, as I see no line in the node console for `authenticated!`, and I don't see the `you are authenticated!` string in the browser console.

**Comment by zacharynevin** [comment]
Hold this issue actually, it seems that none of my emitters work.

**Comment by crmn111** [comment]
So, zacharynevin, did you resolve this? I am interested also in token authentication in combination with express.io

**Comment by sergio11** [comment]
I would like to use token based authentication with socketio-jwt.
how it should proceed to do this ?
